version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" 
    depends_on:
      - backend  

  backend:
    build:
      context: ./
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=True
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
