name: djangoenv
channels:
  - anaconda
  - defaults
dependencies:
  - pillow=8.2.0
  - pip=21.0.1
  - pixman=0.40.0
  - pkginfo=1.7.0
  - pluggy=0.13.1
  - ply=3.11
  - prometheus_client=0.10.1
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py=1.10.0
  - py-lief=0.10.1
  - pycodestyle=2.6.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pycurl=7.43.0.6
  - pydocstyle=6.0.0
  - pyerfa=1.7.3
  - pyflakes=2.2.0
  - pygments=2.8.1
  - pylint=2.7.4
  - pyls-black=0.4.6
  - pyls-spyder=0.3.2
  - pyodbc=4.0.30
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=6.2.3
  - python=3.9.4
  - pip:
      - arrow==1.2.3
      - asgiref==3.6.0
      - binaryornot==0.4.4
      - cookiecutter==1.7.3
      - deprecated==1.2.13
      - django==4.1.7
      - django-allauth==0.52.0
      - django-braces==1.15.0
      - django-cors-headers==3.13.0
      - django-crispy-forms==1.14.0
      - django-extensions==3.2.1
      - django-filter==22.1
      - django-model-utils==4.3.1
      - django-oauth-toolkit==2.2.0
      - django-postman==4.3.1
      - django-rest-auth==0.9.5
      - django-rest-framework-social-oauth2==1.1.0
      - djangorestframework==3.14.0
      - djangorestframework-oauth==1.1.0
      - djangorestframework-simplejwt==5.2.2
      - importlib-metadata==6.0.0
      - jinja2-time==0.2.0
      - jsonfield==3.1.0
      - jwcrypto==1.4.2
      - markdown==3.4.1
      - oauth2-provider==0.0
      - oauthlib==3.2.2
      - poyo==0.5.0
      - psycopg2-binary==2.9.5
      - pydot==1.4.2
      - pyjwt==2.6.0
      - python-slugify==7.0.0
      - python-webpack-boilerplate==1.0.0
      - python3-openid==3.2.0
      - pyzk==0.9
      - requests-oauthlib==1.3.1
      - social-auth-app-django==5.0.0
      - social-auth-core==4.3.0
      - text-unidecode==1.3