# Generated by Django 4.1.7 on 2023-04-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namesurname", models.CharField(max_length=100)),
                ("studentid", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("classs", models.CharField(max_length=100)),
            ],
        ),
    ]
