# Generated by Django 4.1.7 on 2023-04-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="classs", new_name="UserClass",
        ),
        migrations.RenameField(
            model_name="student", old_name="department", new_name="userDepart",
        ),
    ]
