# Generated by Django 4.1.7 on 2023-04-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_classs_student_userclass_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="UserClass", new_name="userClass",
        ),
    ]
