# Generated by Django 4.1.7 on 2023-04-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_others"),
    ]

    operations = [
        migrations.AlterField(
            model_name="others", name="email", field=models.EmailField(max_length=100),
        ),
    ]
