# Generated by Django 4.1.7 on 2023-04-27 06:48

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_others_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="purpose",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, base.models.Purpose["ProductionSupport"]),
                    (2, base.models.Purpose["Education"]),
                    (3, base.models.Purpose["WorkshopUsage"]),
                    (4, base.models.Purpose["Visit"]),
                    (5, base.models.Purpose["Other"]),
                ],
                null=True,
            ),
        ),
    ]
