# Generated by Django 4.1.7 on 2023-09-14 08:10

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_checkin_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="other",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.others",
            ),
        ),
        migrations.AddField(
            model_name="others",
            name="otherId",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="others",
            name="otherType",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, base.models.Purpose["ProductionSupport"]),
                    (2, base.models.Purpose["Education"]),
                    (3, base.models.Purpose["WorkshopUsage"]),
                    (4, base.models.Purpose["Visit"]),
                    (5, base.models.Purpose["Other"]),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.student",
            ),
        ),
    ]
