# Generated by Django 4.1.7 on 2023-09-14 08:23

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_checkin_other_others_otherid_others_othertype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="others",
            name="otherType",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, base.models.OtherType["Student"]),
                    (2, base.models.OtherType["Academician"]),
                    (3, base.models.OtherType["Entrepreneur"]),
                    (4, base.models.OtherType["Other"]),
                ],
                null=True,
            ),
        ),
    ]
